DOMAIN = "usgs_quakes"
DEFAULT_RADIUS = 50.0  # km
DEFAULT_MINIMUM_MAGNITUDE = 0.0
DEFAULT_SCAN_INTERVAL = 300  # seconds
CONF_LATITUDE = "latitude"
CONF_LONGITUDE = "longitude"
CONF_RADIUS = "radius"
CONF_MINIMUM_MAGNITUDE = "minimum_magnitude"
CONF_FEED_TYPE = "feed_type"
